// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/features/tvshow/presentation/bloc/tvshow_detail_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/features/tvshow/domain/entities/tvshow.dart' as _i9;
import 'package:core/features/tvshow/domain/entities/tvshow_detail.dart' as _i7;
import 'package:core/features/tvshow/domain/repositories/tvshow_repository.dart'
    as _i2;
import 'package:core/features/tvshow/domain/usecases/get_tvshow_detail.dart'
    as _i4;
import 'package:core/features/tvshow/domain/usecases/get_tvshow_recommendation.dart'
    as _i8;
import 'package:core/features/tvshow/domain/usecases/get_tvshow_watchlist_status.dart'
    as _i11;
import 'package:core/features/tvshow/domain/usecases/get_watchlist_tvshow.dart'
    as _i10;
import 'package:core/features/tvshow/domain/usecases/remove_tvshow_watchlist.dart'
    as _i13;
import 'package:core/features/tvshow/domain/usecases/save_tvshow_watchlist.dart'
    as _i12;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvShowRepository_0 extends _i1.Fake implements _i2.TvShowRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTvShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowDetail extends _i1.Mock implements _i4.GetTvShowDetail {
  MockGetTvShowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>>.value(
              _FakeEither_1<_i6.Failure, _i7.TvShowDetail>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.TvShowDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTvShowRecommendation].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowRecommendation extends _i1.Mock
    implements _i8.GetTvShowRecommendation {
  MockGetTvShowRecommendation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>.value(
              _FakeEither_1<_i6.Failure, List<_i9.TvShow>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetWatchListTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListTvShow extends _i1.Mock
    implements _i10.GetWatchListTvShow {
  MockGetWatchListTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>.value(
              _FakeEither_1<_i6.Failure, List<_i9.TvShow>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i9.TvShow>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTvShowWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowWatchListStatus extends _i1.Mock
    implements _i11.GetTvShowWatchListStatus {
  MockGetTvShowWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SaveTvShowWatchList].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTvShowWatchList extends _i1.Mock
    implements _i12.SaveTvShowWatchList {
  MockSaveTvShowWatchList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RemoveTvShowWatchList].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTvShowWatchList extends _i1.Mock
    implements _i13.RemoveTvShowWatchList {
  MockRemoveTvShowWatchList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_0()) as _i2.TvShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}
