name: core
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.15.0-268.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  about:
    path: ../about
  build_runner: ^2.1.5
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  encrypt: ^5.0.1
  equatable: ^2.0.2
 # firebase_crashlytics: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_rating_bar: ^4.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  http: ^0.13.3
  mockito: ^5.0.16
  path_provider: ^2.0.2
  provider: ^6.0.0
  search:
    path: ../search
  sqflite_sqlcipher: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
 
  # assets:
  #   - assets/
  #   - assets/cer/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
